# Uptime Kuma monitors configuration - etcd.me overlay
apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-kuma-monitors
  namespace: uptime-kuma
data:
  monitors.json: |
    {
      "monitors": [
        {
          "name": "Keycloak",
          "type": "http",
          "url": "https://auth.etcd.me/realms/homelab",
          "interval": 60,
          "retryInterval": 30,
          "maxretries": 3,
          "description": "Keycloak authentication server"
        },
        {
          "name": "ArgoCD",
          "type": "http",
          "url": "https://argo.etcd.me/healthz",
          "interval": 60,
          "retryInterval": 30,
          "maxretries": 3,
          "description": "ArgoCD GitOps platform"
        },
        {
          "name": "Grafana",
          "type": "http",
          "url": "https://loki.etcd.me/api/health",
          "interval": 60,
          "retryInterval": 30,
          "maxretries": 3,
          "description": "Grafana monitoring dashboard"
        },
        {
          "name": "n8n",
          "type": "http",
          "url": "https://n8n.etcd.me/healthz",
          "interval": 60,
          "retryInterval": 30,
          "maxretries": 3,
          "description": "n8n workflow automation"
        },
        {
          "name": "Uptime Kuma",
          "type": "http",
          "url": "https://uptime.etcd.me/status",
          "interval": 60,
          "retryInterval": 30,
          "maxretries": 3,
          "description": "Uptime Kuma status page"
        },
        {
          "name": "PostgreSQL",
          "type": "port",
          "hostname": "postgres-rw.postgres.svc.cluster.local",
          "port": 5432,
          "interval": 60,
          "retryInterval": 30,
          "maxretries": 3,
          "description": "CloudNative-PG database"
        },
        {
          "name": "Kubernetes API",
          "type": "http",
          "url": "https://kubernetes.default.svc/healthz",
          "ignoreTls": true,
          "interval": 30,
          "retryInterval": 15,
          "maxretries": 3,
          "description": "Kubernetes API server"
        }
      ],
      "statusPage": {
        "slug": "status",
        "title": "etcd.me Status",
        "description": "Service status for etcd.me homelab",
        "showPoweredBy": false,
        "publicGroupList": [
          {
            "name": "Public Services",
            "monitors": ["Keycloak", "ArgoCD", "Grafana", "n8n", "Uptime Kuma"]
          },
          {
            "name": "Infrastructure",
            "monitors": ["PostgreSQL", "Kubernetes API"]
          }
        ]
      }
    }
