# Setup script for Uptime Kuma provisioning
apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-kuma-setup-script
  namespace: uptime-kuma
data:
  setup.py: |
    #!/usr/bin/env python3
    """
    Uptime Kuma setup script - provisions admin account, monitors, and status page.
    Reads configuration from /config/monitors.json
    """
    import os
    import sys
    import json
    import time
    from uptime_kuma_api import UptimeKumaApi, MonitorType

    KUMA_URL = os.environ.get("KUMA_URL", "http://localhost:3001")
    KUMA_USERNAME = os.environ.get("KUMA_USERNAME", "admin")
    KUMA_PASSWORD = os.environ.get("KUMA_PASSWORD", "changeme")
    CONFIG_PATH = "/config/monitors.json"
    MAX_RETRIES = 30
    RETRY_DELAY = 10

    def wait_for_kuma(api):
        """Wait for Uptime Kuma to be ready."""
        for i in range(MAX_RETRIES):
            try:
                info = api.info()
                print(f"Uptime Kuma is ready (version: {info.get('version', 'unknown')})")
                return True
            except Exception as e:
                print(f"Waiting for Uptime Kuma... ({i+1}/{MAX_RETRIES}): {e}")
                time.sleep(RETRY_DELAY)
        return False

    def setup_admin(api):
        """Setup admin account if needed."""
        try:
            # Try to login first
            api.login(KUMA_USERNAME, KUMA_PASSWORD)
            print(f"Logged in as existing user: {KUMA_USERNAME}")
            return True
        except Exception as e:
            if "need setup" in str(e).lower() or "setup" in str(e).lower():
                print("First time setup - creating admin account...")
                try:
                    api.setup(KUMA_USERNAME, KUMA_PASSWORD)
                    print(f"Admin account created: {KUMA_USERNAME}")
                    api.login(KUMA_USERNAME, KUMA_PASSWORD)
                    return True
                except Exception as setup_error:
                    print(f"Setup failed: {setup_error}")
                    return False
            else:
                print(f"Login failed: {e}")
                return False

    def get_monitor_type(type_str):
        """Convert string type to MonitorType enum."""
        type_map = {
            "http": MonitorType.HTTP,
            "port": MonitorType.PORT,
            "ping": MonitorType.PING,
            "keyword": MonitorType.KEYWORD,
            "dns": MonitorType.DNS,
            "push": MonitorType.PUSH,
            "steam": MonitorType.STEAM,
            "mqtt": MonitorType.MQTT,
            "sqlserver": MonitorType.SQLSERVER,
            "postgres": MonitorType.POSTGRES,
            "mysql": MonitorType.MYSQL,
            "mongodb": MonitorType.MONGODB,
            "radius": MonitorType.RADIUS,
            "redis": MonitorType.REDIS,
            "docker": MonitorType.DOCKER,
        }
        return type_map.get(type_str.lower(), MonitorType.HTTP)

    def create_monitors(api, monitors_config):
        """Create monitors from configuration."""
        existing_monitors = {m["name"]: m for m in api.get_monitors()}
        created = 0
        updated = 0

        for monitor in monitors_config:
            name = monitor.get("name")
            monitor_type = get_monitor_type(monitor.get("type", "http"))

            # Build monitor params
            params = {
                "type": monitor_type,
                "name": name,
                "interval": monitor.get("interval", 60),
                "retryInterval": monitor.get("retryInterval", 30),
                "maxretries": monitor.get("maxretries", 3),
            }

            # Add type-specific params
            if monitor_type == MonitorType.HTTP:
                params["url"] = monitor.get("url")
                if monitor.get("ignoreTls"):
                    params["ignoreTls"] = True
            elif monitor_type == MonitorType.PORT:
                params["hostname"] = monitor.get("hostname")
                params["port"] = monitor.get("port")

            # Add description if provided
            if monitor.get("description"):
                params["description"] = monitor.get("description")

            if name in existing_monitors:
                print(f"Monitor '{name}' already exists, updating...")
                try:
                    api.edit_monitor(existing_monitors[name]["id"], **params)
                    updated += 1
                except Exception as e:
                    print(f"  Warning: Could not update '{name}': {e}")
            else:
                print(f"Creating monitor: {name}")
                try:
                    api.add_monitor(**params)
                    created += 1
                except Exception as e:
                    print(f"  Error creating '{name}': {e}")

        print(f"Monitors: {created} created, {updated} updated")
        return created + updated > 0

    def create_status_page(api, status_config, monitors_config):
        """Create public status page."""
        if not status_config:
            print("No status page configuration found")
            return

        slug = status_config.get("slug", "status")
        title = status_config.get("title", "Status")

        # Get all monitors to map names to IDs
        all_monitors = {m["name"]: m["id"] for m in api.get_monitors()}

        # Build public group list with monitor IDs
        public_group_list = []
        for group in status_config.get("publicGroupList", []):
            monitor_ids = []
            for monitor_name in group.get("monitors", []):
                if monitor_name in all_monitors:
                    monitor_ids.append({"id": all_monitors[monitor_name]})
                else:
                    print(f"  Warning: Monitor '{monitor_name}' not found for status page")

            public_group_list.append({
                "name": group.get("name", "Services"),
                "weight": len(public_group_list) + 1,
                "monitorList": monitor_ids
            })

        try:
            # Check if status page exists
            existing_pages = api.get_status_pages()
            page_exists = any(p.get("slug") == slug for p in existing_pages)

            if page_exists:
                print(f"Updating status page: {slug}")
                api.save_status_page(
                    slug=slug,
                    title=title,
                    description=status_config.get("description", ""),
                    showPoweredBy=status_config.get("showPoweredBy", False),
                    publicGroupList=public_group_list
                )
            else:
                print(f"Creating status page: {slug}")
                api.add_status_page(slug, title)
                api.save_status_page(
                    slug=slug,
                    title=title,
                    description=status_config.get("description", ""),
                    showPoweredBy=status_config.get("showPoweredBy", False),
                    publicGroupList=public_group_list
                )
            print(f"Status page configured: /{slug}")
        except Exception as e:
            print(f"Error configuring status page: {e}")

    def main():
        print("=" * 50)
        print("Uptime Kuma Setup")
        print("=" * 50)
        print(f"URL: {KUMA_URL}")
        print(f"Username: {KUMA_USERNAME}")
        print()

        # Load configuration
        try:
            with open(CONFIG_PATH) as f:
                config = json.load(f)
        except Exception as e:
            print(f"Error loading config from {CONFIG_PATH}: {e}")
            sys.exit(1)

        monitors_config = config.get("monitors", [])
        status_config = config.get("statusPage")

        print(f"Loaded {len(monitors_config)} monitor definitions")
        print()

        # Connect to Uptime Kuma
        api = UptimeKumaApi(KUMA_URL)

        try:
            # Wait for Kuma to be ready
            if not wait_for_kuma(api):
                print("ERROR: Uptime Kuma is not responding")
                sys.exit(1)

            # Setup admin account
            if not setup_admin(api):
                print("ERROR: Failed to setup/login admin account")
                sys.exit(1)

            print()

            # Create monitors
            create_monitors(api, monitors_config)

            print()

            # Create status page
            create_status_page(api, status_config, monitors_config)

            print()
            print("=" * 50)
            print("Setup complete!")
            print("=" * 50)

        finally:
            api.disconnect()

    if __name__ == "__main__":
        main()
